#!/usr/bin/env bash

function usage() {
  cat <<EOM

Usage: $(basename $0) [arg1] [arg2]...

    -a      Select apt as the native package manager
    -n      Execute the native package manager (apt, dnf, etc) only
    -y		Confirm all installation beforehand and skip any prompt
    -h      Display this 'help' dialogue

EOM
}

while (($#>0)); do
  case $1 in
    a|-a|--apt)
      SYS_PKG="apt"
      ;;
    n|-n|--native)
      PACUP_MOD="native"
      ;;
    y|-y|--yes)
      PACUP_YES=" -y"
      ;;
    h|-h|--help)
      usage
      exit 0
      ;;
    *)
      usage
      exit 1
      ;;
  esac
  shift
done

function PACUP_APT() {
  echo -e "\nExecuting: sudo apt-get update"
  sudo apt-get update
  echo -e "\nExecuting: sudo apt-get full-upgrade$PACUP_YES"
  sudo apt-get full-upgrade$PACUP_YES
  echo -e "\nExecuting: sudo apt-get autoremove$PACUP_YES --fix broken"
  sudo apt-get autoremove$PACUP_YES --fix-broken
}

function PACUP_SYS() {
  if [ $(command -v snap) ]; then
    echo -e "\nExecuting: sudo snap refresh"
    sudo snap refresh
  fi
  if [ $(command -v brew) ]; then
      brew update
  fi
  if [ $(command -v flatpak) ]; then
    echo -e "\nExecuting: sudo flatpak update$PACUP_YES"
    flatpak update$PACUP_YES
  fi
}

if [ "$SYS_PKG" == "apt" ]; then
  sudo echo -n
  if [ $? != 0 ]; then
    echo -e "\nAPT package manager requires administrator (usually ROOT) privilege.\nPlease try again.\n"
    sudo echo -n
    if [ $? != 0 ]; then
      echo -e "\nAuthentication failure. Quitting..."
      exit 1
    fi
  fi
  PACUP_APT
  exit 0
fi

sudo echo -n
if [ $? != 0 ]; then
  echo -e "\nThis requires administrator (usually ROOT) privileges.\nPlease try again.\n"
  sudo echo -n
  if [ $? != 0 ]; then
    echo -e "\nAuthentication failure. Quitting ..."
    exit 1
  fi
fi

PACUP_APT
PACUP_SYS
echo -e "\nCompleted update"
exit 0
