#!/usr/bin/env bash

# This is a script to let users update user-installed commands.
# oh-my-zsh
if [ $(command -v omz) ]; then
    omz update
fi

# sdkman
if [ $(command -v sdk) ]; then
    sdk update
fi

# rustup
if [ $(command -v rustup) ]; then
    rustup update
fi

# pip?
# pyenv

# rbenv
# ruby-build

# nvm

# yarn
if [ $(test -d $HOME/.yarn) ]; then
    CURR_DIR = `pwd`
    cd $HOME
    yarn upgrade
    cd $CURR_DIR
fi
