name: Verify

on:
  push:
    branches: main
    paths:
      - '.github/workflows/*.yml'
      - 'pacup'
  workflow_dispatch:
    inputs:
      fpk:
        description: "Set up Flatpak"
        type: boolean
        required: true
        default: true

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-20.04
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up and Show help
        run: |
          sudo cp -f ./pacup /usr/local/bin/
          pacup -h
      - if: ${{ github.event.inputs.fpk == 'true' }}
        name: Set up Flatpak
        run: sudo apt install -y flatpak
      - name: Running test
        run: pacup -y
      - if: ${{ github.event.inputs.fpk == 'true' }}
        name: Uninstall Flatpak
        run: sudo apt-get remove -y --purge flatpak
      - if: ${{ github.event.inputs.fpk == 'true' }}
        name: Running test (Remove Flatpak)
        run: pacup -y
      - name: Uninstall Snapd
        run: sudo apt-get remove -y --purge snapd
      - name: Running test (Remove Snapd)
        run: pacup -y
